// Shared popup styling, so every popup reads as one Power-Up rather than
// four separately-styled screens.

export const styles = {
  wrapper: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    padding: "16px",
    boxSizing: "border-box",
    background: "#1D2125",
    color: "#F7F8F9",
  },
  body: { fontSize: 13, color: "#9FADBC", marginBottom: 14, lineHeight: 1.45 },
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 600,
    color: "#9FADBC",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  button: {
    width: "100%",
    padding: "8.5px 14px",
    borderRadius: 6,
    border: "none",
    background: "#579DFF",
    color: "#091E42",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  buttonBusy: { opacity: 0.7, cursor: "default" },
  subtleButton: {
    marginTop: 8,
    background: "none",
    border: "none",
    color: "#85B8FF",
    fontSize: 11.5,
    textDecoration: "underline",
    cursor: "pointer",
    padding: 0,
    width: "100%",
    textAlign: "center",
  },
  error: { fontSize: 12, color: "#F87168", marginTop: 8 },
};

// A dedicated dark theme shown once authorization succeeds and reused by
// Settings — a clean, unified look rather than the light popup flashing
// dark. Matches the modal's own accentColor (#1D2125) so it reads as a
// deliberate screen rather than a mismatch against Trello's dark chrome.
export const successStyles = {
  wrapper: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    background: "#1D2125",
    boxSizing: "border-box",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
  },
  centered: {
    alignItems: "center",
    textAlign: "center",
    padding: "18px 16px 14px",
  },
  iconCircle: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    background: "rgba(75, 206, 151, 0.15)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  title: { fontSize: 14.5, fontWeight: 600, color: "#F7F8F9", margin: "0 0 4px" },
  body: { fontSize: 12.5, color: "#9FADBC", margin: "0 0 16px", lineHeight: 1.45 },
  button: {
    width: "100%",
    padding: "8.5px 14px",
    borderRadius: 6,
    border: "none",
    background: "#579DFF",
    color: "#091E42",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "#9FADBC",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  select: {
    width: "100%",
    padding: "7px 8px",
    borderRadius: 4,
    border: "1px solid #454F59",
    background: "#22272B",
    color: "#F7F8F9",
    fontSize: 13.5,
    boxSizing: "border-box",
  },
  hint: { fontSize: 12.5, color: "#8C9BAB", lineHeight: 1.5, margin: 0 },
  link: {
    marginTop: 10,
    background: "none",
    border: "none",
    color: "#85B8FF",
    fontSize: 12,
    textDecoration: "underline",
    cursor: "pointer",
    padding: 0,
  },
};